version: '3'

services:

  nginx:
    #image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
        - "8080:80"
    volumes:
#        - .drupal:/var/www/drupal
        - .conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
        - php

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
#        - .drupal:/var/www/drupal
        - .conf/php.conf:/etc/php/7.0/fpm/pool.d/www.conf
    ports:
      - 9000:9000

#  memcached:
#    image: memcached:latest
#    environment:
#      # Memcached memory limit in megabytes
#  - MEMCACHED_MEMORY_LIMIT=128

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
        - php
    ports:
      - 3306:3306