FROM debian:latest

COPY .drupal/ /var/www/drupal

RUN chown -R www-data. /var/www/drupal

RUN apt-get update && apt-get install -y \
  php7.0 php7.0-fpm php7.0-mysql php7.0-mbstring php7.0-gd php7.0-xml